name: Update and Compile Singbox Ruleset

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for ruleset update
        id: check-update
        run: |
          set -e
          if [ -f "AWAvenue-Ads-Rule-Singbox.json" ]; then
            LOCAL_SIZE=$(stat -c%s "AWAvenue-Ads-Rule-Singbox.json")
          else
            LOCAL_SIZE=0
          fi
          
          REMOTE_SIZE=$(curl -sI "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json" | grep -i "Content-Length" | awk '{print $2}' | tr -d '\r')
          
          if [ "$LOCAL_SIZE" -ne "$REMOTE_SIZE" ]; then
            echo "::notice::Ruleset has been updated. Proceeding with compilation."
            echo "is_updated=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::Ruleset is already up-to-date. Skipping compilation."
            echo "is_updated=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Download Sing-box
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          set -e
          wget "https://github.com/SagerNet/sing-box/releases/download/v1.12.3/sing-box-1.12.3-linux-amd64.tar.gz"
          tar -xzf sing-box-1.12.3-linux-amd64.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x ./sing-box

      - name: Download JSON Ruleset
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          set -e
          wget "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json" -O AWAvenue-Ads-Rule-Singbox.json

      - name: Compile to SRS
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          set -e
          ./sing-box rule-set compile --output AWAvenue-Ads-Rule-Singbox.srs AWAvenue-Ads-Rule-Singbox.json

      - name: Commit and push changes
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add AWAvenue-Ads-Rule-Singbox.srs
          git commit -m "feat(ruleset): Update and compile AWAvenue-Ads-Rule-Singbox.srs"
          git push
