name: Update and Compile Singbox Ruleset

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for ruleset update
        id: check-update
        run: |
          # 使用 curl 的 -sILf 命令获取远程文件的 Last-Modified 和 Content-Length
          REMOTE_INFO=$(curl -sILf "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json")
          REMOTE_LAST_MODIFIED=$(echo "$REMOTE_INFO" | grep -i "Last-Modified" | awk '{print $NF}')
          REMOTE_CONTENT_LENGTH=$(echo "$REMOTE_INFO" | grep -i "Content-Length" | awk '{print $NF}')

          # 如果本地文件不存在，或者远程文件比本地文件新，则需要更新
          if [ ! -f "AWAvenue-Ads-Rule-Singbox.json" ] || \
             [ "$(date -d "$REMOTE_LAST_MODIFIED" +%s)" -gt "$(date -r "AWAvenue-Ads-Rule-Singbox.json" +%s)" ] || \
             [ "$REMOTE_CONTENT_LENGTH" -ne "$(stat -c%s "AWAvenue-Ads-Rule-Singbox.json" || echo 0)" ]; then
            echo "::notice::Ruleset has been updated. Proceeding with compilation."
            echo "is_updated=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::Ruleset is already up-to-date. Skipping compilation."
            echo "is_updated=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Download and compile ruleset
        # 只有在规则集有更新时才执行此步骤
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          # 下载 sing-box 预编译二进制文件
          wget "https://github.com/SagerNet/sing-box/releases/download/v1.12.3/sing-box-1.12.3-linux-amd64.tar.gz"
          tar -xzf sing-box-1.12.3-linux-amd64.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x ./sing-box
          
          # 下载最新的 JSON 规则集文件
          wget "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json" -O AWAvenue-Ads-Rule-Singbox.json
          
          # 编译成二进制格式 .srs 文件
          ./sing-box rule-set compile --output AWAvenue-Ads-Rule-Singbox.srs AWAvenue-Ads-Rule-Singbox.json
      
      - name: Commit and push changes
        # 只有在规则集有更新时才执行此步骤
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add AWAvenue-Ads-Rule-Singbox.srs
          git commit -m "feat(ruleset): Update and compile AWAvenue-Ads-Rule-Singbox.srs"
          git push
