name: Update and Compile Singbox Ruleset

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download and compile ruleset
        run: |
          wget "https://github.com/SagerNet/sing-box/releases/download/v1.12.3/sing-box-1.12.3-linux-amd64.tar.gz"
          tar -xzf sing-box-1.12.3-linux-amd64.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x ./sing-box
          wget "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json" -O AWAvenue-Ads-Rule-Singbox.json
          ./sing-box rule-set compile --output AWAvenue-Ads-Rule-Singbox.srs AWAvenue-Ads-Rule-Singbox.json

      - name: Check for changes
        id: git-check
        run: |
          git add AWAvenue-Ads-Rule-Singbox.srs
          git diff --quiet --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git commit -m "feat(ruleset): Update and compile AWAvenue-Ads-Rule-Singbox.srs"
          git push
