name: Update and Compile Singbox Ruleset

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 步骤1：检查规则集是否有更新
      - name: Check for ruleset update
        id: check-update
        run: |
          set -e
          # 使用 curl 的 Last-Modified 头部来判断文件是否更新
          REMOTE_LAST_MODIFIED=$(curl -sILf "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json" | grep -i "Last-Modified" | awk '{print $NF}')
          
          if [ ! -f "AWAvenue-Ads-Rule-Singbox.json" ] || [ "$(date -d "$REMOTE_LAST_MODIFIED" +%s)" -gt "$(date -r "AWAvenue-Ads-Rule-Singbox.json" +%s)" ]; then
            echo "::notice::Ruleset has been updated. Proceeding with compilation."
            echo "is_updated=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::Ruleset is already up-to-date. Skipping compilation."
            echo "is_updated=false" >> $GITHUB_OUTPUT
          fi
          
      # 步骤2：仅在规则集有更新时下载并编译
      - name: Download and Compile Ruleset
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          set -e
          # 下载 sing-box 并解压到临时目录
          wget "https://github.com/SagerNet/sing-box/releases/download/v1.12.3/sing-box-1.12.3-linux-amd64.tar.gz"
          tar -xzf sing-box-1.12.3-linux-amd64.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x ./sing-box
          
          # 下载 JSON 规则集文件
          wget "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json" -O AWAvenue-Ads-Rule-Singbox.json
          
          # 编译规则集
          ./sing-box rule-set compile --output AWAvenue-Ads-Rule-Singbox.srs AWAvenue-Ads-Rule-Singbox.json
      
      # 步骤3：仅在规则集有更新时提交更改
      - name: Commit and Push Changes
        if: steps.check-update.outputs.is_updated == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # 检查并添加 srs 文件
          if [ -f "AWAvenue-Ads-Rule-Singbox.srs" ]; then
            git add AWAvenue-Ads-Rule-Singbox.srs
            git commit -m "feat(ruleset): Update and compile AWAvenue-Ads-Rule-Singbox.srs"
            git push
          else
            echo "Error: Compiled .srs file not found."
            exit 1
          fi
